export enum EGearType {
  "Tuna Purse Seines" = "TUNA_PURSE_SEINES",
  "Driftnets" = "DRIFTNETS",
  "Trollers" = "TROLLERS",
  "Set Longlines" = "SET_LONGLINES",
  "Purse Seines" = "PURSE_SEINES",
  "Pots and Traps" = "POTS_AND_TRAPS",
  "Other Fishing" = "OTHER_FISHING",
  "Dredge Fishing" = "DREDGE_FISHING",
  "Set Gillnets" = "SET_GILLNETS",
  "Fixed Gear" = "FIXED_GEAR",
  "Trawlers" = "TRAWLERS",
  "Fishing" = "FISHING",
  "Seiners" = "SEINERS",
  "Other Purse Seines" = "OTHER_PURSE_SEINES",
  "Other Seines" = "OTHER_SEINES",
  "Squid Jigger" = "SQUID_JIGGER",
  "Pole and Line" = "POLE_AND_LINE",
  "Drifting Longlines" = "DRIFTING_LONGLINES",
}

export enum EVessleType {
  Carrier = "CARRIER",
  "Seismic Vessel" = "SEISMIC_VESSEL",
  Passenger = "PASSENGER",
  Other = "OTHER",
  Support = "SUPPORT",
  Bunker = "BUNKER",
  Gear = "GEAR",
  Cargo = "CARGO",
  Fishing = "FISHING",
  Discrepancy = "DISCREPANCY",
  NotApplicable = "",
  NA= "NA"
}

export enum ECountryFlag {
  AFGHANISTAN = "AFG",
  ALBANIA = "ALB",
  ALGERIA = "DZA",
  ANDORRA = "AND",
  ANGOLA = "AGO",
  ANTIGUA_AND_BARBUDA = "ATG",
  ARGENTINA = "ARG",
  ARMENIA = "ARM",
  AUSTRALIA = "AUS",
  AUSTRALIA_CHRISTMAS_ISLAND = "CXR",
  AUSTRALIA_COCOS_ISLANDS = "CCK",
  AUSTRIA = "AUT",
  AZERBAIJAN = "AZE",
  BAHAMAS = "BHS",
  BAHRAIN = "BHR",
  BANGLADESH = "BGD",
  BARBADOS = "BRB",
  BELARUS = "BLR",
  BELGIUM = "BEL",
  BELIZE = "BLZ",
  BENIN = "BEN",
  BHUTAN = "BTN",
  BOLIVIA = "BOL",
  BOSNIA_AND_HERZEGOVINA = "BIH",
  BOTSWANA = "BWA",
  BRAZIL = "BRA",
  BRUNEI = "BRN",
  BULGARIA = "BGR",
  BURKINA_FASO = "BFA",
  BURUNDI = "BDI",
  CABO_VERDE = "CPV",
  CAMBODIA = "KHM",
  CAMEROON = "CMR",
  CANADA = "CAN",
  CENTRAL_AFRICAN_REPUBLIC = "CAF",
  CHAD = "TCD",
  CHILE = "CHL",
  CHINA = "CHN",
  CHINA_HONG_KONG = "HKG",
  CHINA_MACAO = "MAC",
  CHINA_TAIWAN = "TWN",
  COLOMBIA = "COL",
  COMOROS = "COM",
  CONGO = "COG",
  COSTA_RICA = "CRI",
  COTE_DIVOIRE = "CIV",
  CROATIA = "HRV",
  CUBA = "CUB",
  CYPRUS = "CYP",
  CZECH_REPUBLIC = "CZE",
  DPR_KOREA = "PRK",
  DR_CONGO = "COD",
  DENMARK = "DNK",
  DENMARK_FAROE_ISLANDS = "FRO",
  DENMARK_GREENLAND = "GRL",
  DJIBOUTI = "DJI",
  DOMINICA = "DMA",
  DOMINICAN_REPUBLIC = "DOM",
  ECUADOR = "ECU",
  EGYPT = "EGY",
  EL_SALVADOR = "SLV",
  EQUATORIAL_GUINEA = "GNQ",
  ERITREA = "ERI",
  ESTONIA = "EST",
  ESWATINI = "SWZ",
  ETHIOPIA = "ETH",
  FIJI = "FJI",
  FINLAND = "FIN",
  FRANCE = "FRA",
  FRANCE_SOUTHERN_TERRITORIES = "ATF",
  FRANCE_FRENCH_POLYNESIA = "PYF",
  FRANCE_GUADELOUPE = "GLP",
  FRANCE_GUIANA = "GUF",
  FRANCE_MARTINIQUE = "MTQ",
  FRANCE_NEW_CALEDONIA = "NCL",
  FRANCE_REUNION = "REU",
  FRANCE_SAINT_PIERRE = "SPM",
  FRANCE_WALLIS_FUTUNA = "WLF",
  GABON = "GAB",
  GAMBIA = "GMB",
  GEORGIA = "GEO",
  GERMANY = "DEU",
  GHANA = "GHA",
  GREECE = "GRC",
  GRENADA = "GRD",
  GUATEMALA = "GTM",
  GUINEA = "GIN",
  GUINEA_BISSAU = "GNB",
  GUYANA = "GUY",
  HAITI = "HTI",
  HONDURAS = "HND",
  HUNGARY = "HUN",
  ICELAND = "ISL",
  INDIA = "IND",
  INDONESIA = "IDN",
  IRAN = "IRN",
  IRAQ = "IRQ",
  IRELAND = "IRL",
  ISRAEL = "ISR",
  ITALY = "ITA",
  JAMAICA = "JAM",
  JAPAN = "JPN",
  JORDAN = "JOR",
  KAZAKHSTAN = "KAZ",
  KENYA = "KEN",
  KIRIBATI = "KIR",
  KOREA = "KOR",
  KUWAIT = "KWT",
  KYRGYZSTAN = "KGZ",
  LAOS = "LAO",
  LATVIA = "LVA",
  LEBANON = "LBN",
  LESOTHO = "LSO",
  LIBERIA = "LBR",
  LIBYA = "LBY",
  LIECHTENSTEIN = "LIE",
  LITHUANIA = "LTU",
  LUXEMBOURG = "LUX",
  MADAGASCAR = "MDG",
  MALAWI = "MWI",
  MALAYSIA = "MYS",
  MALDIVES = "MDV",
  MALI = "MLI",
  MALTA = "MLT",
  MARSHALL_ISLANDS = "MHL",
  MAURITANIA = "MRT",
  MAURITIUS = "MUS",
  MEXICO = "MEX",
  MICRONESIA = "FSM",
  MOLDOVA = "MDA",
  MONACO = "MCO",
  MONGOLIA = "MNG",
  MONTENEGRO = "MNE",
  MOROCCO = "MAR",
  MOZAMBIQUE = "MOZ",
  MYANMAR = "MMR",
  NAMIBIA = "NAM",
  NAURU = "NRU",
  NEPAL = "NPL",
  NETHERLANDS = "NLD",
  NETHERLANDS_ARUBA = "ABW",
  NETHERLANDS_BES = "BES",
  NETHERLANDS_CURACAO = "CUW",
  NETHERLANDS_SINT_MAARTEN = "SXM",
  NEW_ZEALAND = "NZL",
  NEW_ZEALAND_COOK_ISLANDS = "COK",
  NEW_ZEALAND_NIUE = "NIU",
  NICARAGUA = "NIC",
  NIGER = "NER",
  NIGERIA = "NGA",
  NORTH_MACEDONIA = "MKD",
  NORWAY = "NOR",
  OMAN = "OMN",
  PAKISTAN = "PAK",
  PALAU = "PLW",
  PANAMA = "PAN",
  PAPUA_NEW_GUINEA = "PNG",
  PARAGUAY = "PRY",
  PERU = "PER",
  PHILIPPINES = "PHL",
  POLAND = "POL",
  PORTUGAL = "PRT",
  QATAR = "QAT",
  TURKIYE = "TUR",
  ROMANIA = "ROU",
  RUSSIA = "RUS",
  RWANDA = "RWA",
  SAINT_KITTS_AND_NEVIS = "KNA",
  SAINT_LUCIA = "LCA",
  SAINT_VINCENT = "VCT",
  SAMOA = "WSM",
  SAN_MARINO = "SMR",
  SAO_TOME_AND_PRINCIPE = "STP",
  SAUDI_ARABIA = "SAU",
  SENEGAL = "SEN",
  SERBIA = "SRB",
  SEYCHELLES = "SYC",
  SIERRA_LEONE = "SLE",
  SINGAPORE = "SGP",
  SLOVAKIA = "SVK",
  SLOVENIA = "SVN",
  SOLOMON_ISLANDS = "SLB",
  SOMALIA = "SOM",
  SOUTH_AFRICA = "ZAF",
  SOUTH_SUDAN = "SSD",
  SPAIN = "ESP",
  SRI_LANKA = "LKA",
  PALESTINE = "PSE",
  SUDAN = "SDN",
  SURINAME = "SUR",
  SWEDEN = "SWE",
  SWITZERLAND = "CHE",
  SYRIA = "SYR",
  TAJIKISTAN = "TJK",
  TANZANIA = "TZA",
  THAILAND = "THA",
  TIMOR_LESTE = "TLS",
  TOGO = "TGO",
  TONGA = "TON",
  TRINIDAD_AND_TOBAGO = "TTO",
  TUNISIA = "TUN",
  TURKMENISTAN = "TKM",
  TUVALU = "TUV",
  UGANDA = "UGA",
  UKRAINE = "UKR",
  UAE = "ARE",
  UNITED_KINGDOM = "GBR",
  UK_ANGUILLA = "AIA",
  UK_BERMUDA = "BMU",
  UK_BRITISH_VIRGIN_ISLANDS = "VGB",
  UK_CAYMAN_ISLANDS = "CYM",
  UK_FALKLAND_ISLANDS = "FLK",
  UK_GIBRALTAR = "GIB",
  UK_MONTSERRAT = "MSR",
  UK_PITCAIRN = "PCN",
  UK_SAINT_HELENA = "SHN",
  UK_TURKS_AND_CAICOS = "TCA",
  USA = "USA",
  USA_AMERICAN_SAMOA = "ASM",
  USA_NORTHERN_MARIANA = "MNP",
  USA_PUERTO_RICO = "PRI",
  USA_US_VIRGIN_ISLANDS = "VIR",
  URUGUAY = "URY",
  UZBEKISTAN = "UZB",
  VANUATU = "VUT",
  VATICAN_CITY = "VAT",
  VENEZUELA = "VEN",
  VIETNAM = "VNM",
  YEMEN = "YEM",
  ZAMBIA = "ZMB",
  ZIMBABWE = "ZWE",
}

export enum ENeuralVesselType {
  LikelyNonFishing = "Likely non-fishing",
  LikelyFishing = "Likely fishing",
  OtherUnknown = "Unknown",
}

export enum ESpeedRange {
  LESS_THAN_2 = "<2",
  FROM_2_TO_4 = "2-4",
  FROM_4_TO_6 = "4-6",
  FROM_6_TO_10 = "6-10",
  FROM_10_TO_15 = "10-15",
  FROM_15_TO_25 = "15-25",
  GREATER_THAN_25 = ">25",
}

export enum EFetchMethods {
  post = "POST",
  get = "GET",
}

export enum E4wingsDatasets {
  fishingEffort = "public-global-fishing-effort",
  SARVesselDetections = "public-global-sar-presence",
  AISVesselPresence = "public-global-presence",
}

export const E4wingsDatasetsUI = {
  [E4wingsDatasets.fishingEffort]: "AIS Apparent Fishing Effort",
  [E4wingsDatasets.SARVesselDetections]: "SAR Vessel Detections",
  [E4wingsDatasets.AISVesselPresence]: "AIS Vessel Presence",
} as const;
export type T4wingsDatasetsUI =
  (typeof E4wingsDatasetsUI)[keyof typeof E4wingsDatasetsUI];

export enum EEventDatasets {
  fishingEvent = "public-global-fishing-events",
  encountersEvent = "public-global-encounters-events",
  loiteringEvent = "public-global-loitering-events",
  portVisitsEvent = "public-global-port-visits-events",
  AISOffEvent = "public-global-gaps-events",
}

export enum EContextLayerDatasets {
  eez = "public-eez-areas",
  mpa = "public-mpa-all",
  rfmo = "public-rfmo",
  marineregions = "World_EEZ_20231025_LR",
  wdpa = "WDPA_WDOECM_APR2026",
  bathymetry = "gebco_2025_sub_ice_topo",
}

export enum ERegionDatasets {
  eez = "public-eez-areas",
  mpa = "public-mpa-all",
}

export enum ERegionBufferOperations {
  DIFFERENCE = "DIFFERENCE",
  DISSOLVE = "DISSOLVE",
}

export enum ERegionBufferUnits {
  MILES = "MILES",
  NAUTICALMILES = "NAUTICALMILES",
  KILOMETERS = "KILOMETERS",
  RADIANS = "RADIANS",
  DEGREES = "DEGREES",
}

export enum ESpatialResolution {
  LOW = "LOW",
  HIGH = "HIGH",
}

export enum ETemporalResolution {
  HOURLY = "HOURLY",
  DAILY = "DAILY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
  ENTIRE = "ENTIRE",
}

export enum EFormat {
  CSV = "CSV",
  TIF = "TIF",
  JSON = "JSON",
}

export enum EGroupBy {
  VESSEL_ID = "VESSEL_ID",
  FLAG = "FLAG",
  GEARTYPE = "GEARTYPE",
  FLAGANDGEARTYPE = "FLAGANDGEARTYPE",
  MMSI = "MMSI",
}

export enum EEventType {
  gap = "gap",
  fishing = "fishing",
  encounter = "encounter",
  loitering = "loitering",
  port_visit = "port_visit",
}

export enum EContextLayers {
  eez = "EEZ",
  mpa = "MPA",
  bathymetry = "Bathymetry",
  //rfmo = 'RFMO',
}
