extends:
  - spectral:oas

rules:
  operation-operationId:
    recommended: true

  operation-summary:
    recommended: true

  operation-description:
    recommended: false

  no-$ref-siblings: error
  no-unresolved-refs: error

  oas3-valid-schema-example: error